#!/usr/bin/env php
<?php
/**
 * Big CMS console bootstrap file.
 *
 * @link http://www.bigbrush-agency.com/
 * @copyright Copyright (c) 2015 Big Brush Agency ApS
 * @license http://www.bigbrush-agency.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', false);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/common/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);