<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktiv',
    'Alias' => 'Alias',
    'Are you sure?' => 'Er du sikker?',
    'Blocks' => 'Blokke',
    'block' => 'blok',
    'Categories' => 'Kategorier',
    'Category' => 'Kategori',
    'category' => 'kategori',
    'Choose which form fields to display' => 'Vælg hvilke felter der vises',
    'Close' => 'Luk',
    'Contact form fields' => 'Felter i kontakt form',
    'Content' => 'Indhold',
    'Create {0}' => 'Opret {0}',
    'Created' => 'Oprettet',
    'Created at' => 'Oprettet',
    'Created by' => 'Oprettet af',
    'Default' => 'Standard',
    'Delete' => 'Slet',
    'Edit menus' => 'Rediger menuer',
    'Edit {0}' => 'Rediger {0}',
    'Email' => 'Email',
    'File manager' => 'Mediebibliotek',
    'Home' => 'Forsiden',
    'Inactive' => 'Inaktiv',
    'Info' => 'Info',
    'Insert media' => 'Indsæt medie',
    'Login' => 'Login',
    'Logout' => 'Log ud',
    'Media' => 'Medier',
    'Menu items' => 'Menupunkter',
    'menu item' => 'menupunkt',
    'Menus' => 'Menuer',
    'menu' => 'menu',
    'Message' => 'Besked',
    'Message after a successful form submission' => 'Besked efter kontakt form er sendt',
    'Meta description' => 'Meta beskrivelse',
    'Meta keywords' => 'Meta nøgleord',
    'Meta title' => 'Meta titel',
    'Minimize' => 'Minimer',
    'Name' => 'Navn',
    'New {0}' => 'Ny {0}',
    'No' => 'Nej',
    'Ordering' => 'Rækkefølge',
    'Page' => 'Side',
    'page' => 'side',
    'Page SEO' => 'Side SEO',
    'Pages' => 'Sider',
    'Pages categories' => 'Side kategorier',
    'Password' => 'Adgangskode',
    'Phone' => 'Telefon nr.',
    'Receiver' => 'Modtager',
    'Section' => 'Sektion',
    'Select a link' => 'Vælg et link',
    'Select content' => 'Vælg indhold',
    'Select menu' => 'Vælg menu',
    'Select section' => 'Vælg sektion',
    'Seo' => 'Seo',
    'Show email' => 'Vis email',
    'Show message' => 'Vis besked',
    'Show name' => 'Vis navn',
    'Show phone' => 'Vis telefon nr.',
    'State' => 'Status',
    'Sure?' => 'Sikker?',
    'Template' => 'Skabelon',
    'template' => 'skabelon',
    'Templates' => 'Skabeloner',
    'Title' => 'Titel',
    'Trashed' => 'Smidt ud',
    'Updated' => 'Opdateret',
    'Updated at' => 'Opdateret',
    'Updated by' => 'Opdateret af',
    'Username' => 'Brugernavn',
    'Users' => 'Brugere',
    'user' => 'bruger',
    'Welcome' => 'Velkommen',
    'Welcome to Big CMS' => 'Velkommen til Big CMS',
    'Where to go after form is submitted' => 'Naviger til efter form er sendt',
    'Yes' => 'Ja',
];
