<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Blocks' => 'Blokke',
    'Categories' => 'Kategorier',
    'Create {0}' => 'Opret {0}',
    'Delete' => 'Slet',
    'Edit menus' => 'Rediger menuer',
    'Edit {0}' => 'Rediger {0}',
    'File manager' => 'Mediebibliotek',
    'Home' => 'Forsiden',
    'Info' => 'Info',
    'Logout' => 'Log ud',
    'Menu items' => 'Menupunkter',
    'Menus' => 'Menuer',
    'Minimize' => 'Minimer',
    'New {0}' => 'Ny {0}',
    'Ordering' => 'Rækkefølge',
    'Page' => 'Side',
    'Pages' => 'Sider',
    'Select menu' => 'Vælg menu',
    'Seo' => 'Seo',
    'Templates' => 'Skabeloner',
    'Title' => 'Overskrift',
    'Users' => 'Brugere',
    'Welcome' => 'Velkommen',
    'block' => 'blok',
    'category' => 'kategori',
    'menu' => 'menu',
    'menu item' => 'menupunkt',
    'page' => 'side',
];
